version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app/
      - /app/node_modules
    depends_on:
      - server
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
volumes:
  db-volume:
